axis_linear: 1
scale_linear: 0.1
scale_linear_turbo: 0.6

axis_angular: 0
scale_angular: 0.3
scale_angular_turbo: 0.6

enable_button: 5  # L2 shoulder button
enable_turbo_button: 2  # L1 shoulder button
